[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "roguehostapd"
version = "1.1.2"
description = "Hostapd wrapper for hostapd"
authors = [{ name = "Wifiphisher" }]
license = { text = "BSD-3-Clause" }
requires-python = ">=3.9"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Topic :: System :: Networking",
    "Intended Audience :: Information Technology",
]

[tool.setuptools]
packages = ["roguehostapd", "examples", "roguehostapd.config", "roguehostapd.buildutil"]
package-dir = { "roguehostapd" = "roguehostapd" }

[tool.setuptools.package-data]
roguehostapd = ["config/hostapd.conf", "config/config.ini"]
